// <auto-generated />
using System;
using DoAnASP.Areas.Admin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoAnASP.Migrations
{
    [DbContext(typeof(DPContext))]
    partial class DPContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.ChiTietDatVeModel", b =>
                {
                    b.Property<int>("IdChiTietDatVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("GiaVe")
                        .HasColumnType("float");

                    b.Property<int>("MaDatVe")
                        .HasColumnType("int");

                    b.Property<string>("TenGhe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdChiTietDatVe");

                    b.HasIndex("MaDatVe");

                    b.ToTable("chiTietDatVeModels");
                });

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.DatVeModel", b =>
                {
                    b.Property<int>("IdDatVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaLichChieu")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoGhe")
                        .HasColumnType("int");

                    b.Property<double>("TongGia")
                        .HasColumnType("float");

                    b.Property<bool>("TrangThaiThanhToan")
                        .HasColumnType("bit");

                    b.HasKey("IdDatVe");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaLichChieu");

                    b.ToTable("datVeModels");
                });

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.GheModel", b =>
                {
                    b.Property<int>("IdGhe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaLoaiGhe")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<string>("TenGhe")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdGhe");

                    b.HasIndex("MaLoaiGhe");

                    b.HasIndex("MaPhong");

                    b.ToTable("gheModels");
                });

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.GiamGiaModel", b =>
                {
                    b.Property<int>("IdMaGiamGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PhanTram")
                        .HasColumnType("int");

                    b.HasKey("IdMaGiamGia");

                    b.ToTable("giamGiaModels");
                });

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.LichChieuModel", b =>
                {
                    b.Property<int>("IdLichChieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("GiaVe")
                        .HasColumnType("float");

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<int>("MaGiamGia")
                        .HasColumnType("int");

                    b.Property<int>("MaPhim")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayChieu")
                        .HasColumnType("datetime2");

                    b.HasKey("IdLichChieu");

                    b.HasIndex("MaGiamGia");

                    b.HasIndex("MaPhim");

                    b.HasIndex("MaPhong");

                    b.ToTable("lichChieuModels");
                });

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.LoaiGheModel", b =>
                {
                    b.Property<int>("IdLoaiGhe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("GiaLoaiGhe")
                        .HasColumnType("float");

                    b.Property<string>("TenLoaiGhe")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.HasKey("IdLoaiGhe");

                    b.ToTable("loaiGheModels");
                });

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.LoaiPhimModel", b =>
                {
                    b.Property<int>("IdLoaiPhim")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenLoaiPhim")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("IdLoaiPhim");

                    b.ToTable("loaiPhimModels");
                });

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.PhimModel", b =>
                {
                    b.Property<int>("IdPhim")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("MaLoaiPhim")
                        .HasColumnType("int");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhim")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<TimeSpan>("ThoiLuong")
                        .HasColumnType("time");

                    b.HasKey("IdPhim");

                    b.HasIndex("MaLoaiPhim");

                    b.ToTable("phimModels");
                });

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.PhongModel", b =>
                {
                    b.Property<int>("IdPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaRap")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("IdPhong");

                    b.HasIndex("MaRap");

                    b.ToTable("phongModels");
                });

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.QuanHuyenModel", b =>
                {
                    b.Property<int>("IdQuanHuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaThanhPho")
                        .HasColumnType("int");

                    b.Property<string>("TenQuanHuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("IdQuanHuyen");

                    b.HasIndex("MaThanhPho");

                    b.ToTable("quanHuyenModels");
                });

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.RapModel", b =>
                {
                    b.Property<int>("IdRap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChiRap")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("MaQuanHuyen")
                        .HasColumnType("int");

                    b.Property<string>("TenRap")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("IdRap");

                    b.HasIndex("MaQuanHuyen");

                    b.ToTable("rapModels");
                });

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.ThanhPhoModel", b =>
                {
                    b.Property<int>("IdThanhPho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenThanhPho")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("IdThanhPho");

                    b.ToTable("thanhPhoModels");
                });

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.UserModel", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool>("LoaiTaiKhoan")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("IdUser");

                    b.ToTable("userModels");
                });

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.ChiTietDatVeModel", b =>
                {
                    b.HasOne("DoAnASP.Areas.Admin.Models.DatVeModel", "datVe")
                        .WithMany("lstChiTietDatVe")
                        .HasForeignKey("MaDatVe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.DatVeModel", b =>
                {
                    b.HasOne("DoAnASP.Areas.Admin.Models.UserModel", "khachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnASP.Areas.Admin.Models.LichChieuModel", "lichChieu")
                        .WithMany("lstDatVe")
                        .HasForeignKey("MaLichChieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.GheModel", b =>
                {
                    b.HasOne("DoAnASP.Areas.Admin.Models.LoaiGheModel", "loaiGhe")
                        .WithMany("lstGhe")
                        .HasForeignKey("MaLoaiGhe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnASP.Areas.Admin.Models.PhongModel", "phong")
                        .WithMany("lstGhe")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.LichChieuModel", b =>
                {
                    b.HasOne("DoAnASP.Areas.Admin.Models.GiamGiaModel", "giamGia")
                        .WithMany("lstLichChieu")
                        .HasForeignKey("MaGiamGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnASP.Areas.Admin.Models.PhimModel", "phim")
                        .WithMany("lstLichChieu")
                        .HasForeignKey("MaPhim")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnASP.Areas.Admin.Models.PhongModel", "phong")
                        .WithMany("lstLichChieu")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.PhimModel", b =>
                {
                    b.HasOne("DoAnASP.Areas.Admin.Models.LoaiPhimModel", "loaiPhim")
                        .WithMany("lstPhim")
                        .HasForeignKey("MaLoaiPhim")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.PhongModel", b =>
                {
                    b.HasOne("DoAnASP.Areas.Admin.Models.RapModel", "rap")
                        .WithMany("lstPhong")
                        .HasForeignKey("MaRap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.QuanHuyenModel", b =>
                {
                    b.HasOne("DoAnASP.Areas.Admin.Models.ThanhPhoModel", "thanhPho")
                        .WithMany("lstQuanHuyen")
                        .HasForeignKey("MaThanhPho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoAnASP.Areas.Admin.Models.RapModel", b =>
                {
                    b.HasOne("DoAnASP.Areas.Admin.Models.QuanHuyenModel", "quanHuyen")
                        .WithMany("lstRap")
                        .HasForeignKey("MaQuanHuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
